# -*- coding: utf-8 -*-
"""Random_sample_tweets_20230422.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wNs23ztUWmijViXO0mjC3OBhMLbEFWuB
"""

import pandas as pd
import numpy as np
import os

from google.colab import drive
drive.mount('/content/drive')

working_dir = "/content/drive/Shareddrives/AI Squad/Education Tweets"
os.chdir(working_dir)
os.listdir()

# read in data


df = pd.read_csv('clean_text_mpnet__pca_80_agg_threshold__15_n_comp_5_n_neig_2_20230414_us.csv')
df

df = df.filter(items = ['clean_text'])
df

df = df.dropna()
df

df = df.sample(n=200)
df







df.to_csv('random_tweets_sample_200_20230422.csv')